const accessories = {
	"none": {
		power: 0,
		defense: 0,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 0,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 10,
		maxLvl: 120,
		chartFindable: true,
		jewelSockets: 0,
	}, 
	"calvusCrown": {
		power: 13,
		defense: 0,
		agility: 11,
		intensity: 0,
		size: 11,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1,
		defenseIncrement: 0,
		agilityIncrement: 1,
		intensityIncrement: 0,
		sizeIncrement: 1,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 100,
		maxLvl: 200,
		chartFindable: false,
		jewelSockets: 2,
	},
	"calvusMantello": {
		power: 13,
		defense: 0,
		agility: 11,
		intensity: 0,
		size: 11,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1,
		defenseIncrement: 0,
		agilityIncrement: 1,
		intensityIncrement: 0,
		sizeIncrement: 1,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 100,
		maxLvl: 200,
		chartFindable: false,
		jewelSockets: 2,
	},
	"carinaBracelets":{
		power: 11.3,
		defense: 0,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 13.1,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1.3,
		defenseIncrement: 0,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 1.6,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 90,
		maxLvl: 190,
		chartFindable: false,
		jewelSockets: 2,
	},
	"carinaFaulds":{
		power: 11.3,
		defense: 0,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 13.1,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1.3,
		defenseIncrement: 0,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 1.6,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 90,
		maxLvl: 190,
		chartFindable: false,
		jewelSockets: 2,
	},
	"carinaPauldrons":{
		power: 11.3,
		defense: 0,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 13.1,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1.3,
		defenseIncrement: 0,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 1.6,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 90,
		maxLvl: 190,
		chartFindable: false,
		jewelSockets: 2,
	},
	"cernyxFaulds":{
		power: 0,
		defense: 70.5,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 8.786,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 11.893,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 1.5,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 60,
		maxLvl: 160,
		chartFindable: false,
		jewelSockets: 2,
	},
	"cernyxAmulet":{
		power: 0,
		defense: 101.071,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 8.786,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 16.786,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 1.5,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 60,
		maxLvl: 160,
		chartFindable: false,
		jewelSockets: 0,
	},
	"eliusCape":{
		power: 7.321,
		defense: 0,
		agility: 8.786,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1.321,
		defenseIncrement: 0,
		agilityIncrement: 1.5,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 60,
		maxLvl: 160,
		chartFindable: false,
		jewelSockets: 2,
	},
	"eliusShroud":{
		power: 7.321,
		defense: 0,
		agility: 8.786,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1.321,
		defenseIncrement: 0,
		agilityIncrement: 1.5,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 60,
		maxLvl: 160,
		chartFindable: false,
		jewelSockets: 2,
	},
	"titaniumHelmet":{
		power: 0,
		defense: 121,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 12,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 100,
		maxLvl: 250,
		chartFindable: true,
		jewelSockets: 2,
	},
};

const finalAccessory1 = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var accessory1EnchantValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var accessory1ModifierValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var accessory1Jewels = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

const finalAccessory2 = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var accessory2EnchantValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var accessory2ModifierValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var accessory2Jewels = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

const finalAccessory3 = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var accessory3EnchantValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var accessory3ModifierValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var accessory3Jewels = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}