const chests = {
	"none": {
		power: 0,
		defense: 0,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 0,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 10,
		maxLvl: 120,
		chartFindable: true,
		jewelSockets: 0,
	}, 
	"calvusChest": {
		power: 17,
		defense: 0,
		agility: 14.833,
		intensity: 0,
		size: 14.833,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 2,
		defenseIncrement: 0,
		agilityIncrement: 1.5,
		intensityIncrement: 0,
		sizeIncrement: 1.5,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 100,
		maxLvl: 200,
		chartFindable: false,
		jewelSockets: 2,
	},
	"carinaChest":{
		power: 15,
		defense: 0,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 18,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 2,
		defenseIncrement: 0,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 2,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 90,
		maxLvl: 190,
		chartFindable: false,
		jewelSockets: 2,
	},
	"cernyxChest":{
		power: 0,
		defense: 94.214,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 12,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 15.786,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 2,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 60,
		maxLvl: 160,
		chartFindable: false,
		jewelSockets: 2,
	},
	"eliusChest":{
		power: 10.071,
		defense: 0,
		agility: 12,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1.786,
		defenseIncrement: 0,
		agilityIncrement: 2,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 60,
		maxLvl: 160,
		chartFindable: false,
		jewelSockets: 2,
	},
	"titaniumChest":{
		power: 0,
		defense: 162,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 16,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 100,
		maxLvl: 250,
		chartFindable: true,
		jewelSockets: 2,
	},
};

const finalChest = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var chestEnchantValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var chestModifierValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var chestJewels = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}