const legs = {
	"none": {
		power: 0,
		defense: 0,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 0,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 10,
		maxLvl: 120,
		chartFindable: true,
		jewelSockets: 0,
	}, 
	"calvusLegs": {
		power: 13,
		defense: 0,
		agility: 11,
		intensity: 0,
		size: 11,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1,
		defenseIncrement: 0,
		agilityIncrement: 1,
		intensityIncrement: 0,
		sizeIncrement: 1,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 100,
		maxLvl: 200,
		chartFindable: false,
		jewelSockets: 2,
	}, 
	"carinaLegs":{
		power: 11.3,
		defense: 0,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 13.1,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1.3,
		defenseIncrement: 0,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 1.6,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 90,
		maxLvl: 190,
		chartFindable: false,
		jewelSockets: 2,
	},
	"cernyxLegs":{
		power: 0,
		defense: 70,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 8.321,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 12,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 1.607,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 60,
		maxLvl: 160,
		chartFindable: false,
		jewelSockets: 2,
	},
	"eliusLegs":{
		power: 7.321,
		defense: 0,
		agility: 8.786,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 1.321,
		defenseIncrement: 0,
		agilityIncrement: 1.5,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 60,
		maxLvl: 160,
		chartFindable: false,
		jewelSockets: 2,
	},
	"titaniumLegs":{
		power: 0,
		defense: 121,
		agility: 0,
		intensity: 0,
		size: 0,
		speed: 0,
		insanity: 0,
		warding: 0,
		drawback: 0,
		powerIncrement: 0,
		defenseIncrement: 12,
		agilityIncrement: 0,
		intensityIncrement: 0,
		sizeIncrement: 0,
		speedIncrement: 0,
		insanityIncrement: 0,
		wardingIncrement: 0,
		drawbackIncrement: 0,
		minLvl: 100,
		maxLvl: 250,
		chartFindable: true,
		jewelSockets: 2,
	}
};

const finalLeg = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var legEnchantValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var legModifierValue = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}

var legJewels = {
	power: 0,
	defense: 0,
	agility: 0,
	intensity: 0,
	size: 0,
	speed: 0,
	insanity: 0,
	warding: 0,
	drawback: 0,
}